#!/usr/local/bin/ruby

## Include required gem.
require 'openssl'
require 'base64'
require 'httparty'
require 'builder'
require 'optparse'

## Setup OptionParser to create friendly output, and look for command line options.
command_options = {}
opt_parser = OptionParser.new do |opts|
  opts.banner = "Usage: CacheClear [options]"
  opts.separator  ""
  opts.separator  "Options"
  opts.on("-p","--path PATH","Path to Invalidate") do |p|
    command_options[:path]  = p
  end
  opts.on("-h","--host HOST","Level 3 Hostname") do |h|
    command_options[:host]  = h
  end
end

## Enforce mandatory command line options, and generate an error if they are missing.
begin
  opt_parser.parse!
  mandatory = [:path,:host]
  missing = mandatory.select{ |missing_opt| command_options[missing_opt].nil? }
  if not missing.empty?
    puts "Missing Options: #{missing.join(', ')}"
    puts opt_parser
    exit
  end
rescue OptionParser::InvalidOption, OptionParser::MissingArgument
  puts $!.to_s
  puts opt_parser
  exit
end

## Read in the key, secret, and scope from external file so it is not exposed in the script.
account_params = {}
File.open('secretfile', 'r') do |f|
  f.each_line do |line|
    hkey, hvalue = line.chomp.split("=")
    account_params[hkey.to_sym] = hvalue
  end
end

## Create required variables and headers to be used elsewhere.
date = Time.new.gmtime
date_header = date.strftime("%a" + "," + "\s" + "%d" + "\s" + "%b" + "\s" + "%Y" + "\s" + "%H:%M:%S" + "\s" + "%Z")
http_content_type = "text/xml"
l3_path = command_options[:path]
l3_host = command_options[:host]
l3_scope = account_params[:scope]
l3_secret = account_params[:secret]
l3_key = account_params[:key]
invalidate_url = "https://mediaportal.level3.com:443/api/v1.0/invalidations/" + l3_scope + "/" + l3_host

## Create the XML that will be sent as POST body.
xml_req = ''
x = Builder::XmlMarkup.new(:target => xml_req, :indent => 1)
x.instruct!
x.paths {
  x.path l3_path
}

##  Build authentication header.
signature_data = date_header + "\n" + invalidate_url + "\n" + http_content_type + "\n" + "POST" + "\n" + ""
encoded_hash = Base64.encode64(OpenSSL::HMAC.digest( 'sha1', l3_secret , signature_data ))
auth_header = "MPA" + "\s" + l3_key + ":" + encoded_hash

## Create the HTTP POST request, including required headers and the XML as the POST body.
class Http
  include HTTParty
  debug_output $stdout
end
Http.post(invalidate_url,
    :query => { :force => "true",
                :ignoreCase => "false"},
    :headers => { "Authorization" => auth_header,
                  "Date" => date_header,
                  "Content-Type" => http_content_type,
                  "Content-MD5" => ""},
    :body => xml_req
)